---
  extends: eslint-config-ktsn
  parser: babel-eslint
  env:
    es6: true
  parserOptions:
    ecmaVersion: 6
  plugins:
    - vue
    - flowtype
  rules:
    no-extra-parens: 0
    flowtype/define-flow-type: 1
    flowtype/use-flow-type: 1
